master -> main

diff --git a/.github/workflows/deploy-to-prod.yml b/.github/workflows/deploy-to-prod.yml
--- a/.github/workflows/deploy-to-prod.yml
+++ b/.github/workflows/deploy-to-prod.yml
@@ -13,9 +13,9 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Abort if branch is not master
-        if: github.event.release.target_commitish != 'master'
-        run: echo "Release is not on master, aborting"; exit 1;
+      - name: Abort if branch is not main
+        if: github.event.release.target_commitish != 'main'
+        run: echo "Release is not on main, aborting"; exit 1;
       - name: Setup java
         uses: actions/setup-java@v1
         with:
