Oppdatert workflows

diff --git a/.github/workflows/deploy-to-prod.yml b/.github/workflows/deploy-to-prod.yml
--- a/.github/workflows/deploy-to-prod.yml
+++ b/.github/workflows/deploy-to-prod.yml
@@ -5,22 +5,23 @@ on:
 
 jobs:
   deploy:
+    permissions:
+      contents: "read"
+      id-token: "write"
     runs-on: ubuntu-latest
     environment: prod-fss:personbruker
-    env:
-      version: ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ github.ref_name }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
-      - name: Abort if branch is not main
-        if: github.event.release.target_commitish != 'main'
-        run: echo "Release is not on main, aborting"; exit 1;
+        uses: actions/checkout@v3
+      - name: Abort if branch is not master
+        if: github.event.release.target_commitish != 'master'
+        run: echo "Release is not on master, aborting"; exit 1;
       - name: Setup java
         uses: actions/setup-java@v1
         with:
           java-version: 1.17
       - name: Setup cache
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: '~/.gradle/caches
         ~/.gradle/wrapper'
@@ -28,21 +29,18 @@ jobs:
       - name: Build application
         run: |
           ./gradlew clean build
-      - name: Login to Docker
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Build and push docker image
-        run: |
-          docker build -t ${{ env.version }} .
-          docker push ${{ env.version }}
+        uses: nais/docker-build-push@v0
+        id: docker-build-push
+        with:
+          team: personbruker
+          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
+          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
       - name: Deploy to prod-fss
-        uses: nais/deploy/actions/deploy@master
+        uses: nais/deploy/actions/deploy@v1
         env:
           CLUSTER: prod-fss
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           RESOURCE: ./nais/nais.yaml
-          VAR: version=${{ env.version }}
+          VAR: image=${{steps.docker-build-push.outputs.image}}
           VARS: ./nais/prod-fss/personbruker.json
